name: unittest
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["2.7"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: sudo apt install -y libcurl4-openssl-dev libssl-dev python-opencv
      - run: make setup && pip install opencv-python==4.2.0.32 && make test
